/* ---- the 46 countries, in the order they are filed ---- */
const COUNTRIES = [
{name:"Albania",art:"albania",languages:"Albanian",population:"≈ 2.8 million",bestTime:"May – October",knownFor:["Riviera beaches","Ottoman old towns","Hiking"],landmark:"Berat & the Albanian Riviera"},
{name:"Andorra",art:"andorra",languages:"Catalan",population:"≈ 80,000",bestTime:"December – March · June – September",knownFor:["Skiing","Pyrenees","Duty-free shopping"],landmark:"The Pyrenees"},
{name:"Austria",art:"austria",languages:"German",population:"≈ 9.1 million",bestTime:"May – September · December – March",knownFor:["Alps","Classical music","Coffee houses","Palaces"],landmark:"Schönbrunn Palace & the Alps"},
{name:"Belarus",art:"belarus",languages:"Belarusian, Russian",population:"≈ 9.2 million",bestTime:"May – September",knownFor:["Primeval forest","European bison","Fortresses"],landmark:"Białowieża Forest"},
{name:"Belgium",art:"belgium",languages:"Dutch, French, German",population:"≈ 11.8 million",bestTime:"April – October",knownFor:["Chocolate","Beer","Waffles","Guild houses"],landmark:"Grand-Place, Brussels"},
{name:"Bosnia and Herzegovina",art:"bosnia",languages:"Bosnian, Croatian, Serbian",population:"≈ 3.2 million",bestTime:"May – September",knownFor:["Stari Most","Ottoman bazaars","Rafting"],landmark:"The Mostar bridge"},
{name:"Bulgaria",art:"bulgaria",languages:"Bulgarian",population:"≈ 6.4 million",bestTime:"May – September",knownFor:["Black Sea coast","Monasteries","Rose valley","Skiing"],landmark:"Rila Monastery"},
{name:"Croatia",art:"croatia",languages:"Croatian",population:"≈ 3.9 million",bestTime:"May – September",knownFor:["Adriatic islands","City walls","Waterfalls"],landmark:"Dubrovnik old town"},
{name:"Cyprus",art:"cyprus",languages:"Greek, Turkish",population:"≈ 1.3 million",bestTime:"April – June · September – October",knownFor:["Beaches","Ancient ruins","Halloumi","Sunshine"],landmark:"Aphrodite's Rock"},
{name:"Czech Republic",art:"czechia",languages:"Czech",population:"≈ 10.9 million",bestTime:"April – October",knownFor:["Prague","Castles","Beer","Spa towns"],landmark:"Charles Bridge, Prague"},
{name:"Denmark",art:"denmark",languages:"Danish",population:"≈ 6.0 million",bestTime:"May – September",knownFor:["Design","Cycling","Harbour houses","Pastries"],landmark:"Nyhavn, Copenhagen"},
{name:"Estonia",art:"estonia",languages:"Estonian",population:"≈ 1.4 million",bestTime:"May – September",knownFor:["Medieval Tallinn","Forests","Bogs","Song festivals"],landmark:"Tallinn old town"},
{name:"Finland",art:"finland",languages:"Finnish, Swedish",population:"≈ 5.6 million",bestTime:"June – August · December – March",knownFor:["Saunas","Lakes","Northern lights","Lapland"],landmark:"Lakeland & the aurora"},
{name:"France",art:"france",languages:"French",population:"≈ 68 million",bestTime:"May – September",knownFor:["Art","Food","Fashion","History"],landmark:"Eiffel Tower"},
{name:"Germany",art:"germany",languages:"German",population:"≈ 84 million",bestTime:"May – October",knownFor:["Fairytale castles","Beer gardens","Christmas markets"],landmark:"Neuschwanstein Castle"},
{name:"Greece",art:"greece",languages:"Greek",population:"≈ 10.4 million",bestTime:"April – June · September – October",knownFor:["Islands","Ancient ruins","Mythology","Beaches"],landmark:"Santorini"},
{name:"Hungary",art:"hungary",languages:"Hungarian",population:"≈ 9.6 million",bestTime:"April – October",knownFor:["Thermal baths","Danube views","Paprika","Ruin bars"],landmark:"Hungarian Parliament"},
{name:"Iceland",art:"iceland",languages:"Icelandic",population:"≈ 390,000",bestTime:"June – August · September – March for auroras",knownFor:["Waterfalls","Geysers","Hot springs","Northern lights"],landmark:"Waterfalls & volcanic plains"},
{name:"Ireland",art:"ireland",languages:"English, Irish",population:"≈ 5.3 million",bestTime:"May – September",knownFor:["Sea cliffs","Trad music","Green hills","Pubs"],landmark:"Cliffs of Moher"},
{name:"Italy",art:"italy",languages:"Italian",population:"≈ 59 million",bestTime:"April – June · September – October",knownFor:["Art","Food","Ruins","Coastlines"],landmark:"The Colosseum"},
{name:"Kosovo",art:"kosovo",languages:"Albanian, Serbian",population:"≈ 1.6 million",bestTime:"May – September",knownFor:["Ottoman Prizren","Sharr mountains","Hiking"],landmark:"Prizren & the Sharr range"},
{name:"Latvia",art:"latvia",languages:"Latvian",population:"≈ 1.9 million",bestTime:"May – September",knownFor:["Art nouveau Riga","Baltic beaches","Forests"],landmark:"Riga old town"},
{name:"Liechtenstein",art:"liechtenstein",languages:"German",population:"≈ 40,000",bestTime:"May – September",knownFor:["Vaduz Castle","Alpine hiking","Postage stamps"],landmark:"Vaduz Castle"},
{name:"Lithuania",art:"lithuania",languages:"Lithuanian",population:"≈ 2.9 million",bestTime:"May – September",knownFor:["Hill of Crosses","Baroque Vilnius","Amber","Dunes"],landmark:"Hill of Crosses"},
{name:"Luxembourg",art:"luxembourg",languages:"Luxembourgish, French, German",population:"≈ 670,000",bestTime:"April – October",knownFor:["Fortress gorge","Casemates","Castles"],landmark:"Luxembourg City's gorge"},
{name:"Malta",art:"malta",languages:"Maltese, English",population:"≈ 550,000",bestTime:"April – June · September – November",knownFor:["Valletta","Megalithic temples","Diving","Sunshine"],landmark:"Valletta & the luzzu boats"},
{name:"Moldova",art:"moldova",languages:"Romanian",population:"≈ 2.5 million",bestTime:"May – October",knownFor:["Underground wine cellars","Vineyards","Monasteries"],landmark:"The wine country"},
{name:"Monaco",art:"monaco",languages:"French",population:"≈ 39,000",bestTime:"April – June · September",knownFor:["Grand Prix","Harbour yachts","Casino","Riviera"],landmark:"Port Hercule"},
{name:"Montenegro",art:"montenegro",languages:"Montenegrin",population:"≈ 620,000",bestTime:"May – September",knownFor:["Bay of Kotor","Mountains","Beaches"],landmark:"Bay of Kotor"},
{name:"Netherlands",art:"netherlands",languages:"Dutch",population:"≈ 18 million",bestTime:"April – May for tulips · June – September",knownFor:["Canals","Windmills","Tulips","Cycling"],landmark:"Windmills & tulip fields"},
{name:"North Macedonia",art:"macedonia",languages:"Macedonian, Albanian",population:"≈ 1.8 million",bestTime:"May – September",knownFor:["Lake Ohrid","Cliffside churches","Mountains"],landmark:"Church of St. John at Kaneo"},
{name:"Norway",art:"norway",languages:"Norwegian",population:"≈ 5.5 million",bestTime:"June – August · September – March for auroras",knownFor:["Fjords","Northern lights","Midnight sun","Hiking"],landmark:"The fjords"},
{name:"Poland",art:"poland",languages:"Polish",population:"≈ 37 million",bestTime:"May – September",knownFor:["Kraków","Old market squares","Pierogi","Tatra mountains"],landmark:"Kraków's Main Square"},
{name:"Portugal",art:"portugal",languages:"Portuguese",population:"≈ 10.6 million",bestTime:"March – June · September – October",knownFor:["Lisbon trams","Tiled facades","Surf","Fado"],landmark:"Lisbon's yellow trams"},
{name:"Romania",art:"romania",languages:"Romanian",population:"≈ 19 million",bestTime:"May – September",knownFor:["Transylvania","Castles","Carpathians","Painted monasteries"],landmark:"Bran Castle"},
{name:"Russia",art:"russia",languages:"Russian",population:"≈ 144 million",bestTime:"May – September",knownFor:["Onion domes","Ballet","Museums","Long train rides"],landmark:"St. Basil's Cathedral"},
{name:"San Marino",art:"sanmarino",languages:"Italian",population:"≈ 34,000",bestTime:"May – September",knownFor:["Three towers","Mount Titano","Long views"],landmark:"The three towers of Monte Titano"},
{name:"Serbia",art:"serbia",languages:"Serbian",population:"≈ 6.6 million",bestTime:"May – September",knownFor:["Belgrade nightlife","River fortresses","Brass festivals"],landmark:"Belgrade Fortress"},
{name:"Slovakia",art:"slovakia",languages:"Slovak",population:"≈ 5.4 million",bestTime:"May – September",knownFor:["High Tatras","Castles","Caves"],landmark:"The High Tatras"},
{name:"Slovenia",art:"slovenia",languages:"Slovene",population:"≈ 2.1 million",bestTime:"May – September",knownFor:["Lake Bled","Julian Alps","Caves","Green cities"],landmark:"Lake Bled"},
{name:"Spain",art:"spain",languages:"Spanish",population:"≈ 48 million",bestTime:"April – June · September – October",knownFor:["Architecture","Tapas","Beaches","Flamenco"],landmark:"Sagrada Família"},
{name:"Sweden",art:"sweden",languages:"Swedish",population:"≈ 10.6 million",bestTime:"May – September",knownFor:["Archipelagos","Design","Fika","Northern lights"],landmark:"Stockholm's waterfront"},
{name:"Switzerland",art:"switzerland",languages:"German, French, Italian, Romansh",population:"≈ 8.9 million",bestTime:"June – September · December – March",knownFor:["The Matterhorn","Mountain trains","Chocolate","Lakes"],landmark:"The Matterhorn"},
{name:"Ukraine",art:"ukraine",languages:"Ukrainian",population:"≈ 38 million",bestTime:"May – September",knownFor:["Golden domes","Sunflower fields","Carpathians"],landmark:"St. Sophia's golden domes"},
{name:"United Kingdom",art:"uk",languages:"English",population:"≈ 69 million",bestTime:"May – September",knownFor:["Museums","Castles","Pubs","Coastal paths"],landmark:"Big Ben & the Thames"},
{name:"Vatican City",art:"vatican",languages:"Italian, Latin",population:"≈ 800 residents",bestTime:"April – June · September – October",knownFor:["St. Peter's Basilica","Sistine Chapel","Renaissance art"],landmark:"St. Peter's Basilica"}
];
